### ISSUE TITLE
Version checker runs but operator does not create cluster

### ISSUE THREAD

**Issue by chrislovecnm** [cockroachdb/cockroach-operator#575]
This is a flake I have seen in OpenShift a couple of times using my new e2e test.

This is all of the logs unfortunately

```
{"level":"info","ts":1623430339.9542468,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1623430339.954956,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1623430339.9550157,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting EventSource","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1623430340.056454,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting EventSource","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1623430340.1573,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting EventSource","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1623430340.2584233,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting EventSource","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1623430340.3597455,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting Controller","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster"}
{"level":"info","ts":1623430340.3598483,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting workers","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","worker count":1}
{"level":"info","ts":1623430340.3600054,"logger":"controller.CrdbCluster","msg":"reconciling CockroachDB cluster","CrdbCluster":"test/cockroachdb"}
{"level":"info","ts":1623430340.3601382,"logger":"controller.CrdbCluster","msg":"Running action with index: 1 and  name: VersionCheckerAction","CrdbCluster":"test/cockroachdb"}
{"level":"warn","ts":1623430340.3601544,"logger":"action","msg":"starting to check the crdb version of the container provided","action":"Crdb Version Validator","CrdbCluster":"test/cockroachdb"}
{"level":"warn","ts":1623430340.360184,"logger":"action","msg":"User set image.name, using that field instead of cockroachDBVersion","action":"Crdb Version Validator","CrdbCluster":"test/cockroachdb"}
{"level":"warn","ts":1623430340.5441709,"logger":"action","msg":"created/updated job, stopping request processing","action":"Crdb Version Validator","CrdbCluster":"test/cockroachdb"}
{"level":"info","ts":1623430340.544376,"logger":"controller.CrdbCluster","msg":"request was interrupted","CrdbCluster":"test/cockroachdb"}
```

**Comment by chrislovecnm** [comment]
@keith-mcclellan do you know how to recreate this at all?

**Comment by chrislovecnm** [comment]
Eureka

So the operator crashed while I think installing the database

```logs
I0611 16:52:13.085638       1 request.go:655] Throttling request took 1.034470559s, request: GET:https://172.30.0.1:443/apis/quota.openshift.io/v1?timeout=32s
{"level":"info","ts":1623430334.7453601,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1623430334.7459292,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.7459621,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.7459776,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.745994,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.7460015,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.746009,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.746014,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.746019,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.7460258,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.7460306,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.7460344,"logger":"controller-runtime.injectors-warning","msg":"Injectors are deprecated, and will be removed in v0.10.x"}
{"level":"info","ts":1623430334.7460418,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1623430334.7466216,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1623430334.7467968,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting EventSource","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1623430334.8479333,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting EventSource","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1623430334.9486268,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting EventSource","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1623430335.0500507,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting EventSource","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","source":"kind source: /, Kind="}
{"level":"info","ts":1623430335.1514602,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting Controller","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster"}
{"level":"info","ts":1623430335.1516154,"logger":"controller-runtime.manager.controller.crdbcluster","msg":"Starting workers","reconciler group":"crdb.cockroachlabs.com","reconciler kind":"CrdbCluster","worker count":1}
{"level":"info","ts":1623430335.8939137,"logger":"controller.CrdbCluster","msg":"reconciling CockroachDB cluster","CrdbCluster":"test/cockroachdb"}
{"level":"info","ts":1623430335.9071102,"logger":"controller.CrdbCluster","msg":"reconciling CockroachDB cluster","CrdbCluster":"test/cockroachdb"}
{"level":"info","ts":1623430335.907203,"logger":"controller.CrdbCluster","msg":"Running action with index: 1 and  name: VersionCheckerAction","CrdbCluster":"test/cockroachdb"}
{"level":"warn","ts":1623430335.907213,"logger":"action","msg":"starting to check the crdb version of the container provided","action":"Crdb Version Validator","CrdbCluster":"test/cockroachdb"}
{"level":"warn","ts":1623430335.907286,"logger":"action","msg":"User set image.name, using that field instead of cockroachDBVersion","action":"Crdb Version Validator","CrdbCluster":"test/cockroachdb"}
{"level":"error","ts":1623430336.0414317,"logger":"action","msg":"failed to reconcile job only err","action":"Crdb Version Validator","CrdbCluster":"test/cockroachdb","error":"jobs.batch \"cockroachdb-vcheck-27057172\" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion crdb.cockroachlabs.com/v1alpha1 Kind CrdbCluster: no matches for kind \"CrdbCluster\" in version \"crdb.cockroachlabs.com/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\texternal/com_github_go_logr_zapr/zapr.go:132\ngithub.com/cockroachdb/cockroach-operator/pkg/actor.(*versionChecker).Act\n\tpkg/actor/validate_version.go:125\ngithub.com/cockroachdb/cockroach-operator/pkg/controller.(*ClusterReconciler).Reconcile\n\tpkg/controller/cluster_controller.go:130\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\texternal/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:297\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\texternal/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:252\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2\n\texternal/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:215\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\texternal/io_k8s_apimachinery/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\texternal/io_k8s_apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\texternal/io_k8s_apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\texternal/io_k8s_apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\texternal/io_k8s_apimachinery/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\texternal/io_k8s_apimachinery/pkg/util/wait/wait.go:99"}
{"level":"warn","ts":1623430336.0415676,"logger":"action","msg":"version checker","action":"Crdb Version Validator","CrdbCluster":"test/cockroachdb","job":"cockroachdb-vcheck-27057172"}
E0611 16:52:16.042969       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 388 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1904000, 0x2841ab0)
	external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1904000, 0x2841ab0)
	GOROOT/src/runtime/panic.go:965 +0x1b9
github.com/cockroachdb/cockroach-operator/pkg/actor.IsJobPodRunning(0x1d66578, 0xc0007223f0, 0x1d8b5d8, 0xc0001602c0, 0xc00031a900, 0x1d70368, 0xc0006b5df0, 0xf0917426, 0x28665e0)
	pkg/actor/validate_version.go:321 +0xa6
github.com/cockroachdb/cockroach-operator/pkg/actor.WaitUntilJobPodIsRunning.func1(0xc000201260, 0xc0002126a0)
	pkg/actor/validate_version.go:369 +0x65
github.com/cenkalti/backoff.RetryNotify(0xc000740438, 0x1d38668, 0xc000201260, 0x0, 0x0, 0x0)
	external/com_github_cenkalti_backoff/retry.go:37 +0x1e8
github.com/cenkalti/backoff.Retry(...)
	external/com_github_cenkalti_backoff/retry.go:24
github.com/cockroachdb/cockroach-operator/pkg/actor.WaitUntilJobPodIsRunning(0x1d66578, 0xc0007223f0, 0x1d8b5d8, 0xc0001602c0, 0xc00031a900, 0x1d70368, 0xc0006b5df0, 0x1d8a250, 0xc00031a900)
	pkg/actor/validate_version.go:374 +0x127
github.com/cockroachdb/cockroach-operator/pkg/actor.(*versionChecker).Act(0xc00020b380, 0x1d66578, 0xc0007223f0, 0xc0007099c0, 0x0, 0x0)
	pkg/actor/validate_version.go:147 +0x34d3
github.com/cockroachdb/cockroach-operator/pkg/controller.(*ClusterReconciler).Reconcile(0xc000425840, 0x1d66578, 0xc0007223f0, 0xc00021795c, 0x4, 0xc000217944, 0xb, 0xc000722100, 0x0, 0x0, ...)
	pkg/controller/cluster_controller.go:130 +0x1027
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003e6820, 0x1d664d0, 0xc00078e000, 0x1968ca0, 0xc0006caca0)
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:297 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003e6820, 0x1d664d0, 0xc00078e000, 0x0)
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:252 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1d664d0, 0xc00078e000)
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:215 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000768750)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000741f50, 0x1d2e740, 0xc0008ec300, 0xc00078e001, 0xc0007b2120)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000768750, 0x3b9aca00, 0x0, 0x1, 0xc0007b2120)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1d664d0, 0xc00078e000, 0xc00008c330, 0x3b9aca00, 0x0, 0x1)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1d664d0, 0xc00078e000, 0xc00008c330, 0x3b9aca00)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:212 +0x40d
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x179c946]

goroutine 388 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	external/io_k8s_apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1904000, 0x2841ab0)
	GOROOT/src/runtime/panic.go:965 +0x1b9
github.com/cockroachdb/cockroach-operator/pkg/actor.IsJobPodRunning(0x1d66578, 0xc0007223f0, 0x1d8b5d8, 0xc0001602c0, 0xc00031a900, 0x1d70368, 0xc0006b5df0, 0xf0917426, 0x28665e0)
	pkg/actor/validate_version.go:321 +0xa6
github.com/cockroachdb/cockroach-operator/pkg/actor.WaitUntilJobPodIsRunning.func1(0xc000201260, 0xc0002126a0)
	pkg/actor/validate_version.go:369 +0x65
github.com/cenkalti/backoff.RetryNotify(0xc000740438, 0x1d38668, 0xc000201260, 0x0, 0x0, 0x0)
	external/com_github_cenkalti_backoff/retry.go:37 +0x1e8
github.com/cenkalti/backoff.Retry(...)
	external/com_github_cenkalti_backoff/retry.go:24
github.com/cockroachdb/cockroach-operator/pkg/actor.WaitUntilJobPodIsRunning(0x1d66578, 0xc0007223f0, 0x1d8b5d8, 0xc0001602c0, 0xc00031a900, 0x1d70368, 0xc0006b5df0, 0x1d8a250, 0xc00031a900)
	pkg/actor/validate_version.go:374 +0x127
github.com/cockroachdb/cockroach-operator/pkg/actor.(*versionChecker).Act(0xc00020b380, 0x1d66578, 0xc0007223f0, 0xc0007099c0, 0x0, 0x0)
	pkg/actor/validate_version.go:147 +0x34d3
github.com/cockroachdb/cockroach-operator/pkg/controller.(*ClusterReconciler).Reconcile(0xc000425840, 0x1d66578, 0xc0007223f0, 0xc00021795c, 0x4, 0xc000217944, 0xb, 0xc000722100, 0x0, 0x0, ...)
	pkg/controller/cluster_controller.go:130 +0x1027
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003e6820, 0x1d664d0, 0xc00078e000, 0x1968ca0, 0xc0006caca0)
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:297 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003e6820, 0x1d664d0, 0xc00078e000, 0x0)
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:252 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x1d664d0, 0xc00078e000)
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:215 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000768750)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000741f50, 0x1d2e740, 0xc0008ec300, 0xc00078e001, 0xc0007b2120)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000768750, 0x3b9aca00, 0x0, 0x1, 0xc0007b2120)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1d664d0, 0xc00078e000, 0xc00008c330, 0x3b9aca00, 0x0, 0x1)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1d664d0, 0xc00078e000, 0xc00008c330, 0x3b9aca00)
	external/io_k8s_apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	external/io_k8s_sigs_controller_runtime/pkg/internal/controller/controller.go:212 +0x40d
```

**Comment by chrislovecnm** [comment]
So

https://github.com/cockroachdb/cockroach-operator/blob/a4caa2ac9f75a12d6adc217270bc92cb7f252429/pkg/actor/validate_version.go#L321

We are getting a panic from this line ...

**Comment by chrislovecnm** [comment]
So there are two bugs here:

1. we are getting a panic in validate_version.go
2. when the operator restarts it does not reconcile the crdb that it needs to create.  `{"level":"info","ts":1623430340.544376,"logger":"controller.CrdbCluster","msg":"request was interrupted","CrdbCluster":"test/cockroachdb"}`

**Comment by alinadonisa** [comment]
@chrislovecnm  there is a reference of v1alpha instead of v1
```
"failed to reconcile job only err","action":"Crdb Version Validator","CrdbCluster":"test/cockroachdb","error":"jobs.batch \"cockroachdb-vcheck-27057172\" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion crdb.cockroachlabs.com/v1alpha1 Kind CrdbCluster: no matches for kind \"CrdbCluster\" in version \"crdb.cockroachlabs.com/v1alpha1\"","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\texternal/com_github_go_logr_zapr/zapr.go:132\ngithub.com/cockroachdb/cockroach-operator/pkg/actor.(*versionChecker)
```

**Comment by chrislovecnm** [comment]
>  there is a reference of v1alpha instead of v1
@alinadonisa please explain

**Comment by alinadonisa** [comment]
> > there is a reference of v1alpha instead of v1
> > @alinadonisa please explain

my bad... we are still on v1alpha on the operator, we changed only the k8s apiVersion to v1...

**Comment by alinadonisa** [comment]
@chrislovecnm  this is on Open shift? I found this link that is very similar to our error from the logs: https://access.redhat.com/solutions/5343381

**Comment by MartiUK** [comment]
I'm also seeing this on v2.0.1 but when attempting to update a cluster:

```
{"level":"info","ts":1626371612.1090026,"logger":"controller.CrdbCluster","msg":"reconciling CockroachDB cluster","CrdbCluster":"cockroachdb/xyzdb"}
{"level":"info","ts":1626371612.1090455,"logger":"controller.CrdbCluster","msg":"Running action with index: 1 and  name: VersionCheckerAction","CrdbCluster":"cockroachdb/xyzdb"}
{"level":"warn","ts":1626371612.109061,"logger":"action","msg":"starting to check the crdb version of the container provided","action":"Crdb Version Validator","CrdbCluster":"cockroachdb/xyzdb"}
{"level":"warn","ts":1626371612.1090844,"logger":"action","msg":"User set cockroachDBVersion","action":"Crdb Version Validator","CrdbCluster":"cockroachdb/xyzdb"}
{"level":"warn","ts":1626371612.1091747,"logger":"action","msg":"supported CockroachDBVersion v21.1.5","action":"Crdb Version Validator","CrdbCluster":"cockroachdb/xyzdb"}
{"level":"warn","ts":1626371612.1240668,"logger":"action","msg":"created/updated job, stopping request processing","action":"Crdb Version Validator","CrdbCluster":"cockroachdb/xyzdb"}
{"level":"info","ts":1626371612.1241102,"logger":"controller.CrdbCluster","msg":"request was interrupted","CrdbCluster":"cockroachdb/xyzdb"}
```

**Comment by keith-mcclellan** [comment]
@chrislovecnm looks like some folks are still seeing this in v2.0.1, might be worth some additional research

**Comment by keith-mcclellan** [comment]
@MartiUK if you manually go into your k8s jobs and delete the instances of the version checker job, that should unblock you. @taroface we should document this workaround in "known issues" while we work on a fix.

**Comment by chrislovecnm** [comment]
@MartiUK can you provide information on how to recreate this?

**Comment by MartiUK** [comment]
@chrislovecnm I'm unsure of how I've gotten into this position, from what I can recall both of my clusters were deployed with the latest cockroachdb image (at the time) but on a version of the operator that didn't support them, the operator still went ahead and deployed them anyway, of which I manually initialised the clusters etc. They are both running fine but obviously unmanaged by the operator at the moment.

Ideally I would like to be able to help out some more on this issue specifically but @keith-mcclellan's suggestion has seemed to have fixed the issue above and now I'm having issues with the operator reconciling the statefulset.

Both CRDB resources are in a failed state with `Initialized` being false and the current status being: `failed to reconcile statefulset: Operation cannot be fulfilled on statefulsets.apps "xyzdb": the object has been modified; please apply your changes to the latest version and try again`. The operator is constantly trying to reconcile the sts and is spamming logs using up memory etc.

**Comment by chrislovecnm** [comment]
> Both CRDB resources are in a failed state with Initialized being false and the current status being: failed to reconcile statefulset: Operation cannot be fulfilled on statefulsets.apps "xyzdb": the object has been modified; please apply your changes to the latest version and try again. The operator is constantly trying to reconcile the sts and is spamming logs using up memory etc.

That probably was caused by you initializing the DB manually.  Have not done that before :)

@taroface can we document to not initialize the DB and that the operator does it for you.

**Comment by MartiUK** [comment]
>
> That probably was caused by you initializing the DB manually.  Have not done that before :)
> 
>

Any way of marking the clusters as initialised? I did have a quick look at the code and thought it would handle clusters that were already initialised?
